- project:
    check:
      jobs:
        - openstack-tox-pep8
        - legacy-tempest-aio-client:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
    gate:
      jobs:
        - openstack-tox-pep8
        - legacy-tempest-aio-client:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
