- project:
    check:
      jobs:
        - openstack-tox-pep8
        - legacy-tempest-aio-client:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
        - nuage-neutronclient-osc-tests-functional
    gate:
      jobs:
        - openstack-tox-pep8
        - legacy-tempest-aio-client:
            required-projects:
              - OpenStack/nuage-openstack-neutron
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^setup.cfg$
              - ^tox.ini$
        - nuage-neutronclient-osc-tests-functional
    periodic:
      jobs:
        - nuage-neutronclient-osc-tests-functional

- job:
    name: nuage-neutronclient-osc-tests-functional
    parent: legacy-dsvm-base
    run: playbooks/run.yaml
    post-run: playbooks/post.yaml
    timeout: 9000
    required-projects:
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/python-openstackclient
      - openstack/placement
