- hosts: all
  name: python-openstackclient functional tests
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_NEUTRON=1
          export BRANCH_OVERRIDE=default
          export DEVSTACK_PROJECT_FROM_GIT=python-openstackclient
          export NUAGE_OS_RELEASE=${ZUUL_BRANCH#*/}
          export NODEPOOL_MIRROR_HOST={{ zuul_site_mirror_fqdn }}
          if [ -f /etc/ci/vsp_info.sh ]; then
              source /etc/ci/vsp_info.sh
          fi
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi
          export VSP_RELEASE={{ nuage_vsp_release }}
          export DEVSTACK_GATE_TOPOLOGY=aio
          export DEVSTACK_GATE_LIBVIRT_TYPE=kvm

          # by default devstack-gate will include bunch of projects
          # we dont actually need. We ovewrite project list here
          PROJECTS="openstack/devstack-gate"
          PROJECTS="openstack/devstack $PROJECTS"
          PROJECTS="openstack/cinder $PROJECTS"
          PROJECTS="openstack/glance $PROJECTS"
          PROJECTS="openstack/keystone $PROJECTS"
          PROJECTS="openstack/neutron $PROJECTS"
          PROJECTS="openstack/nova $PROJECTS"
          PROJECTS="openstack/placement $PROJECTS"
          PROJECTS="openstack/python-openstackclient $PROJECTS"
          PROJECTS="openstack/requirements $PROJECTS"
          PROJECTS="OpenStack/nuage-openstack-neutron $PROJECTS"
          PROJECTS="OpenStack/nuage-openstack-neutronclient $PROJECTS"
          export DEVSTACK_GATE_PROJECTS_OVERRIDE="$PROJECTS"

          PRIMARY_IP="{{ hostvars['primary']['ansible_default_ipv4']['address'] }}"

          # add own address and VSD ip to no proxy
          export no_proxy=$no_proxy,${PRIMARY_IP},${VSD_SERVER%%:*}

          # get own ip and derrive cidr for public net from it,
          # to avoid overlap on VSD by multiple gate hosts
          group=$(echo ${PRIMARY_IP} | awk -F.  '{print $3}')
          GW="172.${group}.${PRIMARY_IP##*.}.1"
          export DEVSTACK_GATE_FLOATING_RANGE="172.${group}.${PRIMARY_IP##*.}.0/24"
          export DEVSTACK_GATE_PUBLIC_NETWORK_GATEWAY="${GW}"

          function gate_hook {
              bash -xe $BASE/new/nuage-openstack-neutronclient/devstack/ci/gate_hook.sh
          }
          export -f gate_hook

          function post_test_hook {
              # Configure and run functional tests
              bash -xe $BASE/new/nuage-openstack-neutronclient/devstack/ci/post_test_hook.sh functional
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars | combine(proxy_env) }}'

